"""调整歌手和歌曲排序，并更新评论与歌手字段。"""

from django.db import migrations, models


# Generated by Django 5.2.17 on 2026-08-23 04:12
class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['prefix', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title', 'id']},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='prefix',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
