"""调整评论创建时间字段的默认值。"""

import django.utils.timezone
from django.db import migrations, models


# Generated by Django 5.2.17 on 2026-08-23 04:17
class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_artist_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
