# Generated by Django 5.2.17 on 2026-08-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
